### PR TITLE
add transcripts and add feature to keep only 2 lines of text

### PR DESCRIPTION
**Pull request by thebioengineer**
@dgkeyes

This branch will add the features:
- limit text to only 2 rows, 60 characters wide. 
- Captures a transcript of what was said during the talk while recording

docs output has been updated to capture that info.

### CODE REVIEW

**Comment by dgkeyes** [comment]
Nice!

**Comment by thebioengineer** [comment]
Could you try it out and see if it behaves as you expect?

**Comment by dgkeyes** [comment]
Yep, it works great! The captions only cover two lines and then go to the next screen. I was a bit unclear what the transcript function is so didn't try that out.

**Comment by thebioengineer** [comment]
awesome. thanks for checking that out, @dgkeyes. the transcript functionality is so you can double press "t" and have all the closed captions that had been said during recording copied to your clip board. Figured this could help with transcripts so you don't have to populate it manually for accessibility.

**Comment by dgkeyes** [comment]
Ah, that makes sense, thanks!

**Pull request merged**
